[package]
name = "troubadour_freya"
version = "0.1.0"
edition = "2021"
authors = ["J.P. Hagedoorn AKA Dexterdy Krataigos"]
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
async-channel = "2.3.1"
dioxus = "0.6.3"
duration-human = "0.1.10"
duration-str = "0.17.0"
freya = { version = "0.3.4", features = [
    "devtools",
] }
indexmap = "2.9.0"
rfd = "0.15.3"
tokio = "1.46.1"
troubadour_lib = { path = "../troubadour_lib" }
